name: hydroshoot
channels:
  - openalea3/label/dev
  - openalea3/label/rc
  - openalea3
  - conda-forge
dependencies:
  - openalea.mtg
  - openalea.plantgl
  - openalea.caribu
  - openalea.astk
  - numpy
  - scipy
  - sympy
  - pandas
  - jsonschema
  - pvlib-python
  - pip
  - pip:
      - -e .."[test,doc]"
